site_name: Beacon v2 Project Website
site_description: 'Website for Beacon v2'
site_author: 'Michael Baudis, Laureen Fromont & Beacon Developers'
copyright: '&copy; Copyright 2021-2023, Beacon v2 Documentation Contributors'
repo_name: 'ga4gh-beacon.github.io'
repo_url: https://github.com/ga4gh-beacon/ga4gh-beacon.github.io
edit_uri: edit/main/docs/

repo_icon: " [:fontawesome-brands-github:](https://github.com/ga4gh-beacon/ga4gh-beacon.github.io/tree/main/docs)"
extra_css: [css/theme_overrides.css]

plugins:
  - search
  - macros
  - mermaid2

markdown_extensions:
    - toc:
        toc_depth: 2-3
        permalink: true
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.saneheaders
    - pymdownx.superfences
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - mdx_gh_links:
        user: ga4gh-beacon
        repo: beacon-v2
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid   

nav:
    - Introduction: /
    - News: news
    - FAQ: FAQ
    - Publications: publications
    - People: people
    - Protocols & Minutes: minutes
    - External Links:
        - Beacon API Documentation &#8599;: http://docs.genomebeacons.org
        - Github Repositories &#8599;: https://github.com/ga4gh-beacon/
        - Beacon v2 service registry &#8599;: https://ga4gh-approval-service-registry.ega-archive.org
        - ELIXIR BeaconNetwork &#8599;: https://beacon-network.elixir-europe.org
        - Beacon @ ELIXIR &#8599;: http://www.elixir-europe.org/about-us/implementation-studies/beacons
        - '<div>Progenetix&nbsp;Beacon<span style="color: red; font-weight: 800;">+</span> &#8599;</div>': https://progenetix.org/search/
        - GA4GH &#8599;: http://ga4gh.org
        - GA4GH::SchemaBlocks &#8599;: http://schemablocks.org
        - GA4GH::Discovery &#8599;: http://ga4gh-discovery.github.io

theme:
    custom_dir: extras
    name: material
    palette:
        primary: teal
    logo: img/GA-logo.png
    favicon: img/ga4gh_circle.ico
    icon:
        repo: fontawesome/brands/github-alt 
    features:
        - content.tabs.link
        - search.highlight
        - search.share
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - toc.integrate

# Options
extra:
  excerpt_separator: <!--more-->
  blog_list_length: 100
  news:
    dir: news
  minutes:
    dir: minutes
  publications:
    dir: publications
  contacts:
    dir: people
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/genomebeacons
    - icon: fontawesome/brands/github 
      link: https://github.com/ga4gh-beacon

# https://pypi.org/project/mkdocs-with-pdf/ for more PDF configuration ...
